spring:
    profiles:
        active: dev
    resources.add-mappings: false  
    mvc.throw-exception-if-no-handler-found: true  
    datasource:
        url: jdbc:mysql://localhost:3306/wynkmusic?useUnicode=true&characterEncoding=utf8
        username: root
        password:

    jpa:
        show_sql: true
        hibernate:
            ddl-auto: update
        properties:
                    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect 
