kafka:
  bootstrap-servers: localhost:9092
  topic:
    helloworld: helloworld.t
server:
  session:
    cookie:
      max-age: 10
    timeout: 10 
  port: 8080
  
## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
         url : jdbc:mysql://localhost:3306/concretepage
         username : root
         password : 
  jpa:
    properties:
        hibernate:
             dialect: org.hibernate.dialect.MySQL5Dialect 
             format_sql: true
             
    hibernate:     
        ddl-auto: update  
    show-sql: true       
        
management.security.enabled: false
     
endpoints:
  enabled: false
  beans:
    enabled: true
  info:
    enabled: true
  health:
    enabled: true
  metrics:
    enabled: true             

# for example purposes of Camel version 2.18 and below
com:
  api:
    path: '/camel' 

camel:
  springboot:
    # The Camel context name
    name: ServicesRest

# Binding health checks to a different port
management:
  port: 8081

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true

# The application configuration properties
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s
   